In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv("redacted_data.csv")

target = data["charges"]
features = data.drop(columns="charges")

x_train, x_test, y_train, y_test=train_test_split(features,
                                                  target,
                                                  train_size=0.8,
                                                  test_size=0.2,
                                                  random_state=10
)

features.head()

   smoker  age_group  bmi_group  child_insure
0       2          1          3             1
1       1          1          4             1
2       1          1          4             2
3       1          2          2             1
4       1          2          3             1

In [3]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [4]:
data = x_test
data["charges_pred"]=model.predict(x_test.to_numpy())
data["charges_real"]=y_test
data["error"] = data["charges_real"]-data["charges_pred"]

mse = np.sqrt(np.mean(data["error"]**2))
print(mse)

6800.318664263505

D:\study\AI\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [5]:
data[data.smoker==1].head(30)

,smoker,age_group,bmi_group,child_insure,charges_pred,charges_real,error
589,1,2,5,2,11071.855209,24915.04626,13843.191051
770,1,2,3,1,5922.588432,5266.36560,-656.222832
1088,1,1,4,2,6092.446488,4433.91590,-1658.530588
1157,1,2,3,2,7373.052378,6059.17300,-1313.879378
392,1,1,4,1,4641.982542,23082.95533,18440.972788
307,1,3,3,1,9052.595737,8232.63880,-819.956937
703,1,1,5,2,7941.847904,5428.72770,-2513.120204
504,1,1,5,1,6491.383958,3268.84665,-3222.537308
1164,1,2,3,1,5922.588432,4415.15880,-1507.429632
67,1,3,3,2,10503.059683,7726.85400,-2776.205683
261,1,3,5,2,14201.862514,9432.92530,-4768.937214
267,1,1,3,1,2792.581126,2156.75180,-635.829326
1111,1,2,3,1,5922.588432,6393.60345,471.015018
410,1,2,3,1,5922.588432,5910.94400,-11.644432
953,1,1,1,1,-906.221705,21595.38229,22501.603995
375,1,1,1,1,-906.221705,1621.34020,2527.561905
617,1,3,3,1,9052.595737,8703.45600,-349.139737
514,1,2,4,1,7771.989847,3935.17990,-3836.809947
1009,1,4,4,1,14032.004458,11353.22760,-2678.776858
698,1,4,2,1,10333.201626,11833.78230,1500.580674
339,1,2,4,1,7771.989847,7639.41745,-132.572397
492,1,4,5,1,15881.405873,13831.11520,-2050.290673
225,1,4,5,1,15881.405873,12648.70340,-3232.702473
1172,1,2,3,1,5922.588432,6770.19250,847.604068
932,1,1,4,2,6092.446488,4433.38770,-1659.058788
1108,1,1,3,2,4243.045073,18838.70366,14595.658587
345,1,4,4,1,14032.004458,27000.98473,12968.980272
7,1,2,3,2,7373.052378,7281.50560,-91.546778
264,1,1,4,1,4641.982542,3172.01800,-1469.964542
1154,1,1,4,1,4641.982542,1135.94070,-3506.041842